# Индивидуальное задание

Вариант 12: Осуществить циклический сдвиг элементов прямоугольной матрицы на n элементов вправо или вниз (в зависимости от введенного режима), может быть больше количества элементов в строке или столбце.


In [48]:
import numpy as np

Создадим матрицу случайных чисел

In [49]:
M = np.random.randint (0, 20, (5, 5))
print(M)

[[ 6 10 17  3  7]
 [15 19  6  5  1]
 [ 8  4  9  7 14]
 [18 17  6  3 17]
 [12  7  2 18  0]]


Для циклического сдвига вдоль указанной оси библиотеке numpy есть функция roll()

Данная функция принимает 3 параметра: a - numpy массив shift - определяет число смещений axis - определяет ось смещения

In [50]:
rej_choose = int(input("Введите 0 для сдвига вниз или 1 для сдвига вправо"))
num = int(input("Укажите число на которое необходимо сдвинуть матрицу"))
if rej_choose == 0:
    M = np.roll(M, num, axis = rej_choose) # Сдвиг вниз
    print(M)
elif rej_choose == 1:
    M = np.roll(M, num, axis = rej_choose) # Сдвиг вправо
    print(M)
else:
    print("Error")

[[18 17  6  3 17]
 [12  7  2 18  0]
 [ 6 10 17  3  7]
 [15 19  6  5  1]
 [ 8  4  9  7 14]]
