# Лабораторная работа 3.2. Домашнее задание

### Задание №1

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [7]:
import numpy as np

a = np.arange(1,7) * 2
b = np.array([7, 11, 15, 18, 23, 29])
print((a + b) ** 2)

[  81  225  441  676 1089 1681]


$2.$ Выведите все элементы из первого массива, индексы которых соответствуют индексам тех элементов второго массива, которые больше 12 и дают остаток 3 при делении на 5.

In [10]:
a[np.where ((b > 12) & (b % 5 == 3))]

array([ 8, 10])

*3.* Проверьте условие "Элементы первого массива делятся на 4, элементы второго массива меньше 14". (Подсказка: в результате должен получиться массив с True и False)

In [13]:
(a % 4 == 0) & (b < 14)

array([False,  True, False, False, False, False])

### Задание №2

* Найдите интересный для вас датасет. Например, можно выбрать датасет тут. http://data.un.org/Explorer.aspx (выбираете датасет, жмете на view data, потом download, выбирайте csv формат)
* Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
* Проанализируйте и прокомментируйте содержательно получившиеся результаты
* Все комментарии оформляйте строго в ячейках формата markdown
    

In [17]:
import csv
import numpy as np
with open('world_prices.csv', 'r', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    glob = []
    rus = []
    next(reader)
    for i in reader:
        glob.append(float(i[9]))
        rus.append(float(i[7]))
    stat_glob = np.array(glob)
    stat_rus = np.array(rus)
    print(f"Среднее значение цен в мире {np.mean(stat_glob)}, среднее значение цен в России: {np.mean(stat_rus)}" )
    print(f"Среднее отклонение цен в мире {np.std(stat_glob)}, среднее отклонение цен в России: {np.std(stat_rus)}" )
    print(f"Медиана цен в мире {np.median(stat_glob)}, медиана цен в России: {np.median(stat_rus)}" )
    print(f"Дисперсия цен в мире {np.var(stat_glob)}, дисперсия цен в России: {np.var(stat_rus)}" )

Среднее значение цен в мире 0.1684310699588477, среднее значение цен в России: 0.5174794238683128
Среднее отклонение цен в мире 0.36284116538512023, среднее отклонение цен в России: 0.9494874752338788
Медиана цен в мире 0.08, медиана цен в России: 0.29
Дисперсия цен в мире 0.1316537112980322, дисперсия цен в России: 0.9015264656260055
